
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AcessoADatos
{

using System;
    using System.Collections.Generic;
    
public partial class Factura
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Factura()
    {

        this.DetalleFactura = new List<DetalleFactura>();

    }


    public int numero { get; set; }

    public System.DateTime fecha { get; set; }

    public int idcliente { get; set; }



    public virtual Clientes Clientes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual List<DetalleFactura> DetalleFactura { get; set; }

}

}
