

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AcessoADatos
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class servicios1Entities : DbContext
{
    public servicios1Entities()
        : base("name=servicios1Entities")
    {
            Configuration.ProxyCreationEnabled = false;
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Categoria> Categoria { get; set; }

    public virtual DbSet<Clientes> Clientes { get; set; }

    public virtual DbSet<DetalleFactura> DetalleFactura { get; set; }

    public virtual DbSet<Factura> Factura { get; set; }

    public virtual DbSet<Producto> Producto { get; set; }


    public virtual ObjectResult<SP_Clientes_Result> SP_Clientes()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Clientes_Result>("SP_Clientes");
    }


    public virtual ObjectResult<SP_ClientesCategorias_Result> SP_ClientesCategorias()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ClientesCategorias_Result>("SP_ClientesCategorias");
    }

}

}

